# author: asameshi

openapi: 3.0.0
info:
  title: YUMEMI×PGハッカソン API仕様書
  version: 1.0.0
  description: ハッカソンのAPI仕様書。
servers:
  - url: "http://localhost:8003"
tags:
  - name: Habit
    description: 習慣
paths:
  /auth/signin:
    post:
      tags:
        - auth
      description: ログイン
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: "ユーザーのメールアドレス"
                password:
                  type: string
                  description: "ユーザーのパスワード"
      responses:
        "200":
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "認証トークン"
        "400":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /auth/signup:
    post:
      tags:
        - auth
      description: 新規ユーザー登録
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "ユーザー名"
                email:
                  type: string
                  description: "ユーザーのメールアドレス"
                password:
                  type: string
                  description: "ユーザーのパスワード"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: "ユーザーID"
                  token:
                    type: string
                    description: "認証トークン"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /user:
    post:
      tags:
        - user
      description: ユーザー情報を作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "ユーザー名"
                email:
                  type: string
                  description: "ユーザーのメールアドレス"
                password:
                  type: string
                  description: "ユーザーのパスワード"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: "ユーザーID"
                  token:
                    type: string
                    description: "認証トークン"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /user/{userId}:
    get:
      tags:
        - user
      description: ユーザー情報を取得
      parameters:
        - name: userId
          in: path
          required: true
          description: "ユーザーID"
          schema:
            type: string
      responses:
        "200":
          description: User information
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: "ユーザーID"
                  name:
                    type: string
                    description: "ユーザー名"
                  email:
                    type: string
                    description: "ユーザーのメールアドレス"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /usr/notification:
    post:
      tags:
        - user
      description: 通知を作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: "ユーザーID"
                habitId:
                  type: string
                  description: "習慣ID"
                notificationTime: # 元々はnotificationDateだったが、notificationTimeに変更
                  type: string
                  description: "通知時間"
                notificationContent:
                  type: string
                  description: "通知内容"
                NotificationStatus:
                  type: boolean
                  description: "通知ステータス"
      responses:
        "201":
          description: Notification created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  notificationId:
                    type: string
                    description: "通知ID"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /user/payment/{userId}:
    post:
      tags:
        - user
      description: 支払い情報を作成
      parameters:
        - name: userId
          description: 支払い情報を作成するユーザーID
          in: path
          required: true
          schema: 
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: "ユーザーID"
                creditNumber:
                  type: string
                  description: "クレジットカード番号"
                expirationDate: # 元々はexpireDateだったが、expirationDateに変更
                  type: string
                  description: "有効期限"
                securityCode:
                  type: string
                  description: "セキュリティコード"
      responses:
        "201":
          description: Payment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentId:
                    type: string
                    description: "支払いID"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    put:
      tags:
        - user
      description: 支払い情報を更新
      parameters:
        - name: userId
          in: path
          required: true
          description: "ユーザーID"
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: "ユーザーID"
                creditNumber:
                  type: string
                  description: "クレジットカード番号"
                expirationDate: # 元々はexpireDateだったが、expirationDateに変更
                  type: string
                  description: "有効期限"
                securityCode:
                  type: string
                  description: "セキュリティコード"
      responses:
        "200":
          description: Payment updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentId:
                    type: string
                    description: "支払いID"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "404":
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /log:
    post:
      tags:
        - log
      description: ログを作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: "ユーザーID"
                habitId:
                  type: string
                  description: "習慣ID"
                logDate:
                  type: string
                  description: "日付"
                logContent:
                  type: string
                  description: "ログ内容"
      responses:
        "201":
          description: Log created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  logId:
                    type: string
                    description: "ログID"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /habits:
    get:
      tags:
        - Habit
      description: 習慣化項目を取得する
      parameters:
        - name: user_id
          in: query
          schema: 
            type: integer
          required: true
          description: 習慣化項目を取得するユーザーID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - type: object
                      properties:
                        habit_name:
                          type: string
                          example: 早起き
                        judge_time:
                          type: string
                          example: 08:00
                        payment_money:
                          type: integer
                          example: 500
                        judge_method:
                          type: string
                          example: 位置情報
                        enable_notification:
                          type: boolean
                          example: true
                        payment_method:
                          type: string
                          example: クレジットカード
                    - type: object
                      properties:
                        habit_name:
                          type: string
                          example: 筋トレ
                        judge_time:
                          type: string
                          example: 12:00
                        payment_money:
                          type: integer
                          example: 300
                        judge_method:
                          type: string
                          example: 位置情報
                        enable_notification:
                          type: boolean
                          example: false
                        payment_method:
                          type: string
                          example: クレジットカード
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: user_idが空または存在しません
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ユーザーが存在しません
        '500':
          description: Internal Server Error
    post:
      tags:
        - Habit
      description: 習慣化項目を追加する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                habit_name:
                  type: string
                  example: 筋トレ
                judge_method:
                  type: string
                  example: 位置情報
                enabled_notification:
                  type: string
                  example: true
                judge_time:
                  type: string
                  example: 09:00
                user_id:
                  type: integer
                  example: 2
                payment_money:
                  type: integer
                  example: 500
                payment_method:
                  type: string
                  example: クレジットカード
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 習慣化項目の追加に成功しました
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  habit_name:
                    type: array
                    items:
                      type: string
                      example: この項目は必須です。
        '500':
          description: Internal Server Error
  /habits/{id}:
    put:
      tags:
        - Habit
      description: 習慣化項目を更新する
      parameters:
        - name: id
          in: path
          schema: 
            type: integer
          required: true
          description: 更新する習慣化項目のID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: 
                - habit_name
                - judge_method
                - judge_time
                - enable_notification
                - payment_money
                - payment_method
              properties:
                habit_name:
                  type: string
                  example: 筋トレ
                judge_method:
                  type: string
                  example: 腹筋回数
                judge_time:
                  type: string
                  example: 09:00
                enabled_notification:
                  type: boolean
                  example: true
                payment_money:
                  type: integer
                  example: 500
                payment_method:
                  type: string
                  example: クレジットカード
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: 習慣化項目を更新しました
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: habit_nameが存在しません
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: 習慣化項目が存在しません
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Habit
      description: 習慣化項目を削除する
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: 削除したい習慣化項目のID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 習慣化項目の削除に成功しました
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 習慣化項目が存在しません
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: メソッド "DELETE" は許されていません。
        '500':
          description: Internal Server Error


components:
  schemas:
    BadRequestError:
      type: object
      properties:
        ErrorCode:
          type: number
          description: エラーコード
          example: 400
        ErrorMessageJP:
          type: string
          description: エラーメッセージ（日本語）
          example: "バリデーションエラー"
        ErrorMessageEN:
          type: string
          description: エラーメッセージ（英語）
          example: "validation error"
    NotFoundError:
      type: object
      properties:
        ErrorCode:
          type: number
          description: エラーコード
          example: 404
        ErrorMessageJP:
          type: string
          description: エラーメッセージ（日本語）
          example: "そのスレッドは存在しません。"
        ErrorMessageEN:
          type: string
          description: エラーメッセージ（英語）
          example: "This thread is not exists."
    InternalServerError:
      type: object
      properties:
        ErrorCode:
          type: number
          description: エラーコード
          example: 500
        ErrorMessageJP:
          type: string
          description: エラーメッセージ（日本語）
          example: "サーバでエラーが発生しました。"
        ErrorMessageEN:
          type: string
          description: エラーメッセージ（英語）
          example: "Error occurred at server."