# Generated by Django 3.1.14 on 2025-03-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_name', models.CharField(max_length=100)),
                ('enabled_notification', models.BooleanField(default=True)),
                ('judge_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.CharField(max_length=16)),
                ('expire_date', models.DateTimeField()),
                ('security_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_backend.habits')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateTimeField()),
                ('notification_content', models.CharField(max_length=100)),
                ('notification_status', models.BooleanField(max_length=100)),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_backend.habits')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_backend.users')),
            ],
        ),
        migrations.AddField(
            model_name='habits',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_backend.payment'),
        ),
        migrations.AddField(
            model_name='habits',
            name='period_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_backend.period'),
        ),
        migrations.AddField(
            model_name='habits',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_backend.users'),
        ),
    ]
