# Generated by Django 3.1.14 on 2025-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='judge_method',
            field=models.CharField(default='', max_length=200),
        ),
    ]
