# Generated by Django 3.1.14 on 2025-03-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_backend', '0002_habits_judge_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_backend.payment'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='period_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_backend.period'),
        ),
    ]
