# Generated by Django 3.1.14 on 2025-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_backend', '0003_auto_20250319_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='payment_money',
            field=models.IntegerField(default=0),
        ),
    ]
