# Generated by Django 3.1.14 on 2025-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_backend', '0004_habits_payment_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='payment_method',
            field=models.CharField(default='', max_length=100),
        ),
    ]
