# Generated by Django 3.1.14 on 2025-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_backend', '0005_habits_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='judge_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
